/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pacientiPackage;

import static com.sun.org.apache.xalan.internal.xsltc.compiler.util.Type.Int;
import mediciPackage.*;
import databaseConnection.Database;
import java.sql.CallableStatement;
import java.sql.Connection;
import static java.sql.JDBCType.NULL;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import models.FisaModel;
import models.MediciModel;
import models.PacientiModel;
import models.SimptomeModel;

/**
 *
 * @author Calancea Bianca
 */
public class CautarePacientAvansata extends javax.swing.JFrame {

    /**
     * Creates new form CautareMedicAvansata
     */
    public CautarePacientAvansata() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rehreshButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        adaugaButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        footerLabel = new javax.swing.JLabel();
        numeTextField = new javax.swing.JTextField();
        paginaPrincipala = new javax.swing.JButton();
        prenumeTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        prenumeLabel = new javax.swing.JLabel();
        varstaLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        varstaSpinner = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rehreshButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Calancea Bianca\\Desktop\\img sgbd\\refresh.png")); // NOI18N
        rehreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rehreshButtonActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        headerLabel.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        headerLabel.setForeground(new java.awt.Color(255, 255, 255));
        headerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Calancea Bianca\\Desktop\\img sgbd\\icon.jpg")); // NOI18N
        headerLabel.setText("Sistem de gestiune medicala");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        adaugaButton.setBackground(new java.awt.Color(0, 153, 153));
        adaugaButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        adaugaButton.setForeground(new java.awt.Color(255, 255, 255));
        adaugaButton.setText("Cauta");
        adaugaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adaugaButtonActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));

        footerLabel.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        footerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        footerLabel.setText("Copyright Calancea Bianca & Andronic Andra");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(footerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(footerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        numeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeTextFieldActionPerformed(evt);
            }
        });

        paginaPrincipala.setBackground(new java.awt.Color(0, 153, 153));
        paginaPrincipala.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        paginaPrincipala.setForeground(new java.awt.Color(255, 255, 255));
        paginaPrincipala.setIcon(new javax.swing.ImageIcon("C:\\Users\\Calancea Bianca\\Desktop\\img sgbd\\back.jpg")); // NOI18N
        paginaPrincipala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paginaPrincipalaActionPerformed(evt);
            }
        });

        prenumeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prenumeTextFieldActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel1.setText("Aici poti cauta un pacient in baza noastra de date!");

        nameLabel.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        nameLabel.setText("Nume:");

        prenumeLabel.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        prenumeLabel.setText("Prenume:");

        varstaLabel.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        varstaLabel.setText("Varsta:");

        area.setBackground(new java.awt.Color(240, 240, 240));
        area.setColumns(20);
        area.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        area.setRows(5);
        jScrollPane1.setViewportView(area);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(paginaPrincipala, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(39, 39, 39)
                                                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(varstaLabel)
                                                    .addComponent(prenumeLabel))
                                                .addGap(30, 30, 30)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(adaugaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(prenumeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                                                .addComponent(numeTextField)
                                                .addComponent(varstaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addComponent(rehreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameLabel)
                            .addComponent(numeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(paginaPrincipala, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(rehreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(prenumeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prenumeLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(varstaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(varstaLabel))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adaugaButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rehreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rehreshButtonActionPerformed
        this.setVisible(false);
        new CautarePacientAvansata().setVisible(true);
    }//GEN-LAST:event_rehreshButtonActionPerformed

    private void adaugaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adaugaButtonActionPerformed
 ArrayList<PacientiModel> pacientiList=new ArrayList<>();
  ArrayList<FisaModel>fisaList=new ArrayList<>();
  ArrayList<SimptomeModel>simptomeList=new ArrayList<>();
        String nume=numeTextField.getText().trim();
        String prenume=prenumeTextField.getText().trim();
        int varsta=(Integer)varstaSpinner.getValue();
        
        if(numeTextField.getText().isEmpty() || prenumeTextField.getText().isEmpty() || (Integer)varstaSpinner.getValue()==0) 
            {String mesaj="Va rugam introduceti toate campurile!\n";
            area.setText(mesaj); 
            return;}
        String query="select *  from pacienti where nume=? and prenume=? and varsta=?";
        Connection con = Database.getConnection();
        PreparedStatement searchCommand;
        try {
            searchCommand = con.prepareStatement(query);
            searchCommand.setString(1, nume);
            searchCommand.setString(2, prenume);
            searchCommand.setInt(3, varsta);
            searchCommand.executeUpdate();
            ResultSet set=searchCommand.executeQuery();
            PacientiModel pacient;
            if(!set.next()) 
            {String mesaj="Pacientul nu a fost gasit in baza de date!\n";
            area.setText(mesaj);}
            
            do
            {
                pacient=new PacientiModel(set.getInt("ID"),set.getString("nume"),set.getString("prenume"),set.getInt("varsta"),set.getString("sex"),set.getInt("inaltime"),set.getInt("greutate"),set.getString("telefon"));
                pacientiList.add(pacient);
                
                String mesaj1="Pacientul pe care l-ati cautat are urmatoarea fisa: \n";
                mesaj1+= "Nume: "+pacient.getNume()+"\n";
                mesaj1+="Prenume: "+ pacient.getPrenume()+"\n";
                mesaj1+="Varsta: "+ pacient.getVarsta()+"\n";
                mesaj1+="Sex: "+ pacient.getSex()+"\n";
                mesaj1+="Inaltime: "+ pacient.getInaltime()+"\n";
                mesaj1+="Greutate: "+ pacient.getGreutate()+"\n";
                mesaj1+="Telefon: "+ pacient.getTelefon()+"\n";
               
                String query2="select *  from fisa where id_pacient=?";
      
              PreparedStatement search1;
        try {
            search1 = con.prepareStatement(query2);
            search1.setInt(1, pacient.getId());
            search1.executeUpdate();
            ResultSet set2=search1.executeQuery();
            FisaModel fisa;
            if(!set2.next()) 
            {String mesaj="Pacientul nu a fost gasit in baza de date!\n";
            area.setText(mesaj);}
            do
            {
                fisa=new FisaModel(set2.getInt("ID"),set2.getInt("id_pacient"),set2.getInt("id_simptom"));
                fisaList.add(fisa);
                
                
                String query3="select *  from simptome where id=?";
      
              PreparedStatement search2;
        try {
            search2 = con.prepareStatement(query3);
            search2.setInt(1, fisa.getIdSimptom());
            search2.executeUpdate();
            ResultSet set3=search2.executeQuery();
            SimptomeModel simptom;
            if(!set3.next()) 
            {String mesaj="Pacientul nu a fost gasit in baza de date!\n";
            area.setText(mesaj);}
            do
            {
               simptom=new SimptomeModel(set3.getInt("ID"),set3.getString("descriere"));
                simptomeList.add(simptom);
                area.setText(mesaj1+"Simptom: "+ simptom.getDescriere());
            }while(set3.next());  
             } catch (SQLException ex) {
           // Logger.getLogger(CautarePacientDupaNume.class.getName()).log(Level.SEVERE, null, ex);
        }  
            }while(set2.next()); 
             } catch (SQLException ex) {
               // Logger.getLogger(CautarePacientDupaNume.class.getName()).log(Level.SEVERE, null, ex);
            }
            }while(set.next()); 
                } catch (SQLException ex) {
            //Logger.getLogger(CautarePacientDupaNume.class.getName()).log(Level.SEVERE, null, ex);
        }
        

    }//GEN-LAST:event_adaugaButtonActionPerformed

    private void paginaPrincipalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paginaPrincipalaActionPerformed
        new CautarePacient().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_paginaPrincipalaActionPerformed

    private void numeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeTextFieldActionPerformed

    private void prenumeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prenumeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prenumeTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CautarePacientAvansata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CautarePacientAvansata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CautarePacientAvansata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CautarePacientAvansata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CautarePacientAvansata().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adaugaButton;
    private javax.swing.JTextArea area;
    private javax.swing.JLabel footerLabel;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField numeTextField;
    private javax.swing.JButton paginaPrincipala;
    private javax.swing.JLabel prenumeLabel;
    private javax.swing.JTextField prenumeTextField;
    private javax.swing.JButton rehreshButton;
    private javax.swing.JLabel varstaLabel;
    private javax.swing.JSpinner varstaSpinner;
    // End of variables declaration//GEN-END:variables
}
